name: Build and test

on:
  push:
    branches:
      - master
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    name: Build and test
    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Build with dotnet
        run: dotnet build --configuration Release
        shell: bash
        
      - name: Install EF core tool
        run: dotnet tool install --global dotnet-ef
        shell: bash
        
      - name: Run postgres database for testing
        run: make setup_db_for_test
        shell: bash
        
      - name: Unit tests
        run: dotnet test --no-restore --verbosity normal
        shell: bash